import { Geist, Geist_Mono, Dela_Gothic_One, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Container from "./components/packageContainers";
import LenisProvider from "./components/lenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const delaGothicOne = Dela_Gothic_One({
  weight: ["400"],
  variable: "--font-dela-gothic-one",
  subsets: ["latin"],
});

const syne = Syne({
  // weight: ["400", "500", "600", "700", "800"],
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portflio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className="overflow-y-scrolls">
      <body
        className={`${syne.variable} ${delaGothicOne.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-base-300 font-syne max-w-[2000px] mx-auto`}
      >
        <LenisProvider>
          <main className="md:flex">
            <Navbar />
            <div className="flex-1 -order-1">
              {children}
            </div>
          </main>
          <Container />
        </LenisProvider>
      </body>
    </html>
  );
}
