import { Geist, Geist_Mono, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Container from "./components/packageContainers";
import LenisProvider from "./components/lenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  // weight: ["400", "500", "600", "700", "800"],
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portflio | Mohammad Yasin",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/logo1.ico" },
  ],
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="bumblebee" className="overflow-y-scrolls">
      <body
        className={`${syne.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-base-300 font-syne max-w-[2000px] mx-auto selection:bg-info/50`}
      >
        <LenisProvider>
          <main className="md:flex">
            <Navbar />
            <div className="flex-1 -order-1">
              {children}
            </div>
          </main>
          <Container />
        </LenisProvider>
      </body>
    </html>
  );
}
